# Generated by Django 4.0.1 on 2022-02-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20, verbose_name='Car make')),
                ('production_year', models.DateField(verbose_name='Production year')),
                ('plate_numbers', models.CharField(max_length=20, verbose_name='License plate numbers')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='InsuranceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50, verbose_name='Department name')),
            ],
            options={
                'verbose_name': 'Insurance department',
                'verbose_name_plural': 'Insurance departments',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_content', models.CharField(max_length=200, verbose_name='The content of the task')),
                ('task_importance', models.IntegerField(verbose_name='Priority of task')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.insuranceagent', verbose_name='Assigned agent')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('payment_date', models.DateField(verbose_name='Payment date')),
                ('payment_due_date', models.DateField(verbose_name='Payment due date')),
                ('payment_purpose', models.CharField(max_length=200, verbose_name='Payment purpose')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.client', verbose_name='Payer')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_content', models.CharField(max_length=200, verbose_name='Content of notification')),
                ('notification_importance', models.IntegerField(verbose_name='Importance of notification')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.insuranceagent', verbose_name='Assigned agent')),
                ('assigned_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.AddField(
            model_name='insuranceagent',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.insurancedepartment', verbose_name='Insurance Department'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=30, verbose_name='Number of policy')),
                ('policy_type', models.CharField(choices=[('NNW', 'NNW'), ('Autocasco', 'Autocasco'), ('Assistance', 'Assistance'), ('OC', 'OC')], default='OC', max_length=10, verbose_name='Type of policy')),
                ('policy_end_date', models.DateField(verbose_name='Policy expiry date')),
                ('insured_car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.car', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurance',
            },
        ),
        migrations.CreateModel(
            name='DeparmentBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.insurancedepartment', verbose_name='Insurance Department')),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_explanation', models.CharField(max_length=200, verbose_name='Damage explanation')),
                ('damage_date', models.DateField(verbose_name='Date the damage was caused')),
                ('damage_cost', models.IntegerField(verbose_name='Damage cost')),
                ('assigned_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Damage',
                'verbose_name_plural': 'Damage',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.client', verbose_name='Car owner'),
        ),
    ]
