# Generated by Django 4.0.1 on 2022-02-27 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
        migrations.AddField(
            model_name='client',
            name='owned_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.car', verbose_name='Owned car'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insured_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.car', verbose_name='Insured car'),
        ),
    ]
