# Generated by Django 4.0.1 on 2022-02-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20)),
                ('production_year', models.DateField()),
                ('plate_numbers', models.CharField(max_length=20)),
            ],
        ),
    ]
