# Generated by Django 4.0.1 on 2022-02-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_car'),
    ]

    operations = [
        migrations.RenameModel('Person', 'Client')
    ]
