# Generated by Django 4.0.1 on 2022-02-08 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='insurance_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.insurance'),
        ),
    ]
